---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# css-prefix: "icon-"             # prefix for css-generated classes
# demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global resize + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   resize: 0.68                  # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - glyph1_file:                # file name, without extention
#       code: 0xNNN               # Symbol code 0x - hex
#       css: icon-gpyph1-name     # For generated CSS
#       search: [word1, word2]    # Search aliases (array). CSS name will be
#                                 # included automatically
#
#       #
#       # local transformations, only for this glyph (optional)
#       #
#       transform:                # personal glyph transformation.
#         resize_rel              # *_rel - applyed after global.
#         offset: 0.2             # without *_rel - override global
#
################################################################################
#

